### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by gpoitch** [gpoitch/ember-cli-less#29]
Looking for maintainers to add to the repo, or hand over to ember-cli itself, as I will no longer be providing updates.

The latest release is in full working order.  Any breakage may be due to changes in ember-cli itself.

**Comment by knownasilya** [comment]
I'd be willing to be a contributor.

**Comment by gdub22** [comment]
@knownasilya thanks! added you.  I also have a PR coming that adds a dummy app test

**Comment by gpoitch** [comment]
@knownasilya Would you like me to transfer the repo to your account?  I have no intention of maintaining this anymore

**Comment by gpoitch** [comment]
@knownasilya great, can you delete your fork and ill transfer

**Comment by knownasilya** [comment]
All set
