### ISSUE TITLE
Addon optionally bring in bower Less files

### ISSUE THREAD

**Issue by Panman8201** [gpoitch/ember-cli-less#47]
I'm wrapping a bootstrap library that has both CSS and Less files in its bower package. Do you know if it's possible for an addon to _optionally_ use Less? It seems like you _must_ define ember-cli-less as a dependency for an `addon/styles/addon.less` to be imported/compiled. But what I'd like to happen is, if the user has ember-cli-less installed into their _project_, have the `addon.less` file brought in, else fall back on the CSS files. (I know how to do the CSS part..)

**Comment by knownasilya** [comment]
I'm assuming you'd have to do some broccoli tree and manual processing of the less file. Closing this since it's rather old and hasn't seen any other activity.

**Comment by Panman8201** [comment]
Wow, this _does_ go back. Yeah, I basically had the addon look for `ember-cli-less` and setup the import paths for Less files. That's changed now, to Sass, but basically the same idea applies.
