### ISSUE TITLE
Tests fail in Circle due to LESS compilation using Ember 2.10.0

### ISSUE THREAD

**Issue by morgan** [gpoitch/ember-cli-less#53]
Experiencing an issue running tests in Circle. Traced it down to LESS compilation. We are importing large less files which have compiled and worked across multiple versions of Ember CLI.

Ember CLI out-of-the-box passing:

https://github.com/caxiam/ember-cli-less-fail
https://circleci.com/gh/caxiam/ember-cli-less-fail/3

Branch with subset creating failure:

https://github.com/caxiam/ember-cli-less-fail/compare/example-less-failure
https://circleci.com/gh/caxiam/ember-cli-less-fail/4

Thank you!

**Comment by knownasilya** [comment]
Rather old, so closing.
