### ISSUE TITLE
Ember Engines support

### ISSUE THREAD

**Issue by knownasilya** [gpoitch/ember-cli-less#55]
Currently neither sass or less support engines. This is a placeholder issue for when we know how to support them.

**Comment by mike183** [comment]
What is actually the issue with this? I have used LESS in an engine (though extremely lightly), and it seems to have worked.

**Comment by knownasilya** [comment]
I think this can probably be closed now 👍

**Comment by mike183** [comment]
Though I think I recall needing to include both `addon/styles/addon.less` and `app/styles/app.less` in order to get it working...I'd need to double check and see what error it gave though.
