### ISSUE TITLE
JavaScript Heap Out of Memory on Ember CLI Less after 'ember build'

### ISSUE THREAD

**Issue by shortthirdman** [gpoitch/ember-cli-less#60]
I have been experiencing this issue since the last few days ever since I have upgraded my Ember App with all latest versions of dependencies.
Here is the configuration of the app I have upgraded:
`node     6.11.0`
`npm      3.10.10`
`os          Win 8 Pro win32 x64`
`ember-cli    2.11.0`
`ember         2.11.0`
`ember-data  2.11.0`
`ember-cli-less  1.5.3`

Also included is the screenshot of the error on cmd

![screenshot 6](https://user-images.githubusercontent.com/5894985/29626867-cc9a2582-884d-11e7-9782-87d084184f59.png)

**Comment by knownasilya** [comment]
Does it always crash with less?

**Comment by shortthirdman** [comment]
@knownasilya yes..It is breaking with `ember-cli-less` version higher than 1.5.2. I have reverted back to 1.5.0

**Comment by efx** [comment]
@shortthirdman are you able to link to the app or detail how many and how large each  `.less` file is? I'm curious about this kind of performance issue.

**Comment by knownasilya** [comment]
@jasonmit any ideas?

**Comment by shortthirdman** [comment]
@efx Each LESS file is around 10-12 KB. and there are 17 LESS files in all

**Comment by shortthirdman** [comment]
Since my issue has been solved after migrating to Ember CLI Less 1.5.0. I am closing this issue. If other issues found related to this, anyone could repoen the same for more discussion.
