### ISSUE TITLE
module unification app with relative @import LESS files won't build

### ISSUE THREAD

**Issue by efx** [gpoitch/ember-cli-less#62]
I recently ran the `ember-module-migrator` to migrate our app to the improved structure.
`ember build` fails because of a LESS Compiler error:
```
Build Canceled: Broccoli Builder ran into an error with `LessCompiler` plugin. 💥
'routes/some-route.less' wasn't found.
```
Our app uses relative LESS imports like so:
```less
// line from src/ui/styles/app.less
// these files exist in src/ui/styles/routes
@import "routes/some-route.less";
```
This relates to https://github.com/emberjs/ember.js/issues/16373

**Comment by knownasilya** [comment]
Closing since MU was discontinued for smaller incremental changes
