### ISSUE TITLE
Bootstrap panel.less not found issue

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [gpoitch/ember-cli-less#69]
I am using "ember-cli-less": "^1.5.7" - for my ember app and I get the  panel.less not found issue because of  the path problem (I guess). But it works fine when I lock the version to just use 1.5.7 instead of ^1.5.7.

 Could you please check?

error: FileError: '../../../node_modules/bootstrap/less/panels.less' wasn't found. Tried - /codebuild/output/src527386755/src/github.com/ConnectedHomes/ember-home-services/tmp/less_compiler-input_base_path-awXR9UDm.tmp/node_modules/bootstrap/less/panels.less,/codebuild/output/src527386755/src/github.com/ConnectedHomes/ember-home-services/node_modules/bootstrap/less/panels.less,/codebuild/output/src527386755/src/github.com/ConnectedHomes/ember-home-services/node_modules/bootstrap/less/panels.less,../../../node_modules/bootstrap/less/panels.less in /codebuild/output/src527386755/src/github.com/ConnectedHomes/ember-home-services/tmp/less_compiler-input_base_path-awXR9UDm.tmp/0/components/bg-panel/styl… Show more

**Comment by knownasilya** [comment]
What does your import code look like for panel, and where are you importing from?

**Comment by vinodhrajamuralidharan** [comment]
yes, I am importing this and was working fine. Now it is not working now.

**Comment by knownasilya** [comment]
@vinodhrajamuralidharan can you paste an example of what the import looks like?

**Comment by knownasilya** [comment]
I think bootstrap removed less from their bundles, maybe try https://www.npmjs.com/package/bootstrap-less
